
version: 2

sources:
  - name: raw_schema
    database: ECOMMERCE_DB
    schema: RAW_SCHEMA
    tables:
      - name: orders_report
        description: "Orders data from source system"
      - name: products_report
        description: "Products data from source system"
      - name: revenues_report
        description: "Revenues data from source system"